spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
